name: Build and Push Docker Image

on:
  push:
    paths:
      - 'user-management/go.mod'
      - 'user-management/go.sum'
      - 'user-management/main.go'
      - 'user-management/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
           fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID}}
          REGISTRY: us-central1-docker.pkg.dev
          IMAGE_NAME: iamlohit-gcr/user-management
          TAG: latest
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$PROJECT_ID/$IMAGE_NAME:$TAG -f user-management/Dockerfile . --push
