name: Build and Push Docker Image

on:
  push:
    paths:
      - 'user-management/**'
      - 'user-management/go.mod'
      - 'user-management/go.sum'
      - 'user-management/main.go'
      - 'user-management/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
           fetch-depth: 0

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with Google Artifact Registry
        run: |
          gcloud auth configure-docker / us-central1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          REGISTRY: us-central1-docker.pkg.dev
          IMAGE_NAME: iamlohit-gcr/user-management
          TAG: latest
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$PROJECT_ID/$IMAGE_NAME:$TAG -f user-management/Dockerfile . --push
